services:
  app:
    build: .
    ports:
      - "80:80"
    environment:
      - DATABASE_URL=postgres://postgres:1234@db:5432/postgres
      - JWT_SECRET=your_jwt_secret
      - SECURITY_WEBHOOK_URL=http://app:80/webhooks 
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend

  db:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    volumes:
      - ./swagger:/usr/share/nginx/html/swagger
    environment:
      - SWAGGER_JSON=/usr/share/nginx/html/swagger/swagger.yml
      - URLS_PRIMARY_NAME=API Docs 
    depends_on:
      - app
    networks:
      - backend

networks:
  backend:
    driver: bridge 

volumes:
  postgres_data: